const header=`<div class="topbar"><div class="wrap topinner"><span>📈 Al Fayed Stocks — نظرة أوضح للسوق</span><span>السعودي 🇸🇦 | الأمريكي 🇺🇸</span></div></div><header><div class="wrap nav"><a class="brand" href="index.html"><b>Al Fayed</b> <span>Stocks</span><small>MARKETS • ANALYSIS • NEWS</small></a><button class="menu" onclick="document.body.classList.toggle('nav-open')">☰</button><nav><a href="index.html">الرئيسية</a><a href="saudi.html">السعودي</a><a href="usa.html">الأمريكي</a><a href="analysis.html">التحليلات</a><a href="news.html">الأخبار</a><a href="watchlist.html">المراقبة ⭐</a><a href="index.html#contact">تواصل معنا</a></nav><a class="goldbtn" href="index.html#contact">ابدأ الآن</a></div></header>`;
const footer=`<footer><div class="wrap footgrid"><div><div class="brand footerbrand">Al Fayed <span>Stocks</span></div><p>تحليل • أسواق • أخبار</p><p class="muted">محتوى تعليمي ومعلوماتي، وليس توصية استثمارية شخصية.</p></div><div><h4>روابط سريعة</h4><a href="saudi.html">السوق السعودي</a><a href="usa.html">السوق الأمريكي</a><a href="analysis.html">التحليلات</a><a href="news.html">الأخبار</a></div><div><h4>الخدمات</h4><a href="index.html#services">تحليل الأسهم</a><a href="index.html#services">متابعة الأسواق</a><a href="watchlist.html">قائمة المراقبة</a><a href="index.html#contact">تواصل معنا</a></div></div><div class="copyright">© 2026 Al Fayed Stocks — جميع الحقوق محفوظة</div></footer>`;

document.addEventListener('DOMContentLoaded',()=>{let h=document.getElementById('site-header'),f=document.getElementById('site-footer');if(h)h.innerHTML=header;if(f)f.innerHTML=footer;renderWatch();setDates();highlightNav();});
function setDates(){document.querySelectorAll('[data-today]').forEach(el=>el.textContent=new Intl.DateTimeFormat('ar-EG',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()));}
function highlightNav(){const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('nav a').forEach(a=>{const href=a.getAttribute('href');if(href&&href.split('#')[0]===p)a.classList.add('active');});}
function sendContact(e){e.preventDefault();const m=document.getElementById('formmsg');m.textContent='تم تسجيل الطلب مبدئيًا. اربط النموذج بالبريد أو واتساب قبل الإطلاق التجاري.';m.style.color='#1b9a5a';}
function filterCards(type,btn){document.querySelectorAll('.filterbtn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.analysiscard').forEach(c=>c.style.display=(type==='all'||c.classList.contains(type))?'block':'none');}
function addTicker(){let x=document.getElementById('tickerInput'),v=x.value.trim().toUpperCase();if(!v)return;let a=JSON.parse(localStorage.getItem('af_watch')||'[]');if(!a.includes(v))a.push(v);localStorage.setItem('af_watch',JSON.stringify(a));x.value='';renderWatch();}
function renderWatch(){let box=document.getElementById('watchList');if(!box)return;let a=JSON.parse(localStorage.getItem('af_watch')||'[]');box.innerHTML=a.length?a.map((v,i)=>`<div class="watchitem"><div><b>${v}</b><small>مضاف إلى قائمة المتابعة</small></div><button onclick="removeTicker(${i})">حذف</button></div>`).join(''):'<div class="card" style="grid-column:1/-1">قائمة المراقبة فارغة. أضف أول سهم أو مؤشر تريد متابعته.</div>'}
function removeTicker(i){let a=JSON.parse(localStorage.getItem('af_watch')||'[]');a.splice(i,1);localStorage.setItem('af_watch',JSON.stringify(a));renderWatch();}
